import { useEffect, useMemo, useRef, useState } from 'react';
import { API_URL } from '../config';

const Avatar = ({ name }) => <span className="avatar-initial">{name?.[0]?.toUpperCase() || '?'}</span>;
const stamp = (date) => new Date(date).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });

function PostList({ posts, scheduled, canDelete, onDelete, admin }) {
  if (!posts.length) return <p className="empty-state">No posts here yet.</p>;
  return <div className="feed-list">{posts.map((post) => <article key={post.id} className="feed-item">
    <div className="feed-item-header"><div className="feed-item-user"><div className="feed-item-avatar"><Avatar name={post.user_name} /></div><div><b>{post.user_name || 'You'}</b>{admin && <small>{post.user_email}</small>}<small>{scheduled ? `Scheduled ${stamp(post.scheduled_at)}` : stamp(post.published_at || post.created_at)}</small></div></div>{canDelete && <button className="delete-post" onClick={() => onDelete(post.id)}>Delete</button>}</div>
    {post.content && <div className="feed-item-content">{post.content}</div>}{post.media_url && <img src={`${API_URL}${post.media_url}`} alt="Post attachment" className="feed-item-media" />}
  </article>)}</div>;
}

export default function Dashboard({ user, token, onLogout }) {
  const [tab, setTab] = useState('compose'); const [content, setContent] = useState(''); const [audience, setAudience] = useState('public');
  const [scheduledAt, setScheduledAt] = useState(''); const [image, setImage] = useState(null); const [preview, setPreview] = useState(null);
  const [posts, setPosts] = useState([]); const [scheduled, setScheduled] = useState([]); const [admin, setAdmin] = useState(null); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const input = useRef(null); const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]);
  const api = async (path, options = {}) => fetch(`${API_URL}${path}`, { ...options, headers: { ...headers, ...options.headers } });
  const loadPosts = async () => { const r = await api('/api/posts'); if (r.ok) setPosts(await r.json()); };
  const loadScheduled = async () => { const r = await api('/api/posts/scheduled'); if (r.ok) setScheduled(await r.json()); };
  const loadAdmin = async () => { const r = await api('/api/posts/admin/overview'); if (r.ok) setAdmin(await r.json()); };
  useEffect(() => { loadPosts(); loadScheduled(); }, [token]);
  useEffect(() => { if (tab === 'admin' && user.role === 'admin') loadAdmin(); }, [tab, user.role]);
  const selectImage = (event) => { const file = event.target.files?.[0]; if (!file?.type.startsWith('image/')) return; setImage(file); setPreview(URL.createObjectURL(file)); };
  const submit = async (event) => { event.preventDefault(); if (!content.trim() && !image) return; setBusy(true); setNotice(''); const body = new FormData(); body.append('content', content); body.append('audience', audience); if (scheduledAt) body.append('scheduledAt', new Date(scheduledAt).toISOString()); if (image) body.append('image', image);
    try { const r = await api('/api/posts', { method: 'POST', body }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Could not save post'); data.status === 'scheduled' ? setScheduled((x) => [...x, data]) : setPosts((x) => [data, ...x]); setNotice(data.status === 'scheduled' ? 'Post added to calendar.' : 'Post published.'); setContent(''); setScheduledAt(''); setImage(null); setPreview(null); if (input.current) input.current.value = ''; } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const remove = async (id) => { if (!window.confirm('Delete this post?')) return; const r = await api(`/api/posts/${id}`, { method: 'DELETE' }); if (r.ok) { setPosts((x) => x.filter((p) => p.id !== id)); setScheduled((x) => x.filter((p) => p.id !== id)); if (tab === 'admin') loadAdmin(); } };
  const days = Array.from({ length: 7 }, (_, i) => new Date(Date.now() + i * 86400000));
  return <div className="app-container"><header className="header-nav"><div className="brand-logo-container"><div className="brand-icon-wrapper"><span className="material-symbols-outlined">bubble_chart</span></div><span className="brand-title">Aura Studio</span></div><nav className="top-tabs"><button className={tab === 'compose' ? 'selected' : ''} onClick={() => setTab('compose')}>Compose</button><button className={tab === 'calendar' ? 'selected' : ''} onClick={() => setTab('calendar')}>Calendar</button>{user.role === 'admin' && <button className={tab === 'admin' ? 'selected' : ''} onClick={() => setTab('admin')}>Admin</button>}</nav><div className="header-user"><span className="mini-avatar"><Avatar name={user.name} /></span><span>{user.name}</span><button className="logout-icon-btn" onClick={onLogout}><span className="material-symbols-outlined">logout</span></button></div></header>
    <main className="dashboard-container">{notice && <div className="notice-banner">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {tab === 'compose' && <><section className="composer-card"><div className="composer-heading"><div className="avatar-wrapper"><Avatar name={user.name} /></div><div><b>Create a post</b><p>Share now or plan it for later.</p></div></div><form onSubmit={submit}><textarea className="composer-textarea" maxLength="280" placeholder="What's on your mind?" value={content} onChange={(e) => setContent(e.target.value)} /><div className="composer-meta"><span>{content.length}/280</span><button type="button" className="audience-pill" onClick={() => setAudience(audience === 'public' ? 'private' : 'public')}>{audience === 'public' ? 'Public' : 'Private'}</button></div>{preview && <div className="image-preview-container"><img src={preview} alt="Selected attachment" className="image-preview" /><button className="remove-image-btn" type="button" onClick={() => { setImage(null); setPreview(null); }}>×</button></div>}<div className="schedule-row"><label><span className="material-symbols-outlined">calendar_month</span><input aria-label="Schedule date and time" type="datetime-local" min={new Date(Date.now() + 60000).toISOString().slice(0, 16)} value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></label><button className="toolbar-btn" type="button" onClick={() => input.current?.click()}><span className="material-symbols-outlined">image</span></button><input ref={input} className="hidden-file-input" type="file" accept="image/*" onChange={selectImage} /><button className="post-submit-btn active-submit" disabled={busy || (!content.trim() && !image)}>{busy ? 'Saving…' : scheduledAt ? 'Schedule post' : 'Publish post'}</button></div></form></section><section><h2 className="feed-header">Published feed</h2><PostList posts={posts} /></section></>}
      {tab === 'calendar' && <section><div className="section-heading"><div><h1>Content calendar</h1><p>Scheduled posts stay private until publication.</p></div><button className="btn-small" onClick={() => setTab('compose')}>New post</button></div><div className="calendar-grid">{days.map((day) => <div className="calendar-day" key={day.toDateString()}><strong>{day.toLocaleDateString(undefined, { weekday: 'short' })}</strong><span>{day.getDate()}</span>{scheduled.filter((p) => new Date(p.scheduled_at).toDateString() === day.toDateString()).map((p) => <article className="calendar-post" key={p.id}><time>{new Date(p.scheduled_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time><p>{p.content || 'Image post'}</p><button onClick={() => remove(p.id)}>×</button></article>)}</div>)}</div><h2 className="feed-header">Upcoming</h2><PostList posts={scheduled} scheduled canDelete onDelete={remove} /></section>}
      {tab === 'admin' && user.role === 'admin' && <section><div className="section-heading"><div><h1>Admin panel</h1><p>Workspace health and content oversight.</p></div><button className="btn-small" onClick={loadAdmin}>Refresh</button></div>{admin ? <><div className="metric-grid">{Object.entries(admin.metrics).map(([name, value]) => <div className="metric-card" key={name}><span>{name}</span><b>{value}</b></div>)}</div><h2 className="feed-header">Recent workspace activity</h2><PostList posts={admin.posts} canDelete onDelete={remove} admin /></> : <p className="empty-state">Loading workspace overview…</p>}</section>}
    </main></div>;
}
